name: delta
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  get_it: ^7.2.0
  build_runner: ^2.3.3
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  firebase_core: ^2.7.1
  fl_chart: ^0.61.0
  flutter_spinkit: ^5.1.0
  animations: ^2.0.7
  intl: ^0.17.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

